const Images = {
  icon_back: require('../image/icon_back.png'),
  icon_control_full_screen: require('../image/icon_control_full_screen.png'),
  icon_control_pause: require('../image/icon_control_pause.png'),
  icon_control_play: require('../image/icon_control_play.png'),
  icon_control_shrink_screen: require('../image/icon_control_shrink_screen.png'),
  icon_control_slider: require('../image/icon_control_slider.png'),
  icon_right: require('../image/icon_right.png'),
  icon_share_copylink: require('../image/icon_share_copylink.png'),
  icon_share_qq: require('../image/icon_share_qq.png'),
  icon_share_qzone: require('../image/icon_share_qzone.png'),
  icon_share_sina: require('../image/icon_share_sina.png'),
  icon_share_wxsession: require('../image/icon_share_wxsession.png'),
  icon_share_wxtimeline: require('../image/icon_share_wxtimeline.png'),
  icon_video_airplay: require('../image/icon_video_airplay.png'),
  icon_video_capture: require('../image/icon_video_capture.png'),
  icon_video_collected: require('../image/icon_video_collected.png'),
  icon_video_download: require('../image/icon_video_download.png'),
  icon_video_favorite: require('../image/icon_video_favorite.png'),
  icon_video_lock: require('../image/icon_video_lock.png'),
  icon_video_more: require('../image/icon_video_more.png'),
  icon_video_mute: require('../image/icon_video_mute.png'),
  icon_video_muted: require('../image/icon_video_muted.png'),
  icon_video_pause: require('../image/icon_video_pause.png'),
  icon_video_play: require('../image/icon_video_play.png'),
  icon_video_share: require('../image/icon_video_share.png'),
  icon_volume_off: require('../image/icon_volume_off.png'),
  icon_volume_up: require('../image/icon_volume_up.png'),
  img_bottom_shadow: require('../image/img_bottom_shadow.png'),
  img_top_shadow: require('../image/img_top_shadow.png'),
  muted_on: require('../image/muted_on.png'),
  muted_off: require('../image/muted_off.png')
}

export default Images
